POST {{base_url}}/profileAccess HTTP/1.1
# POST http://localhost:3333/profileAccess
Content-Type: {{contentType}}

{
  "name": "Profile 2",
  "active": false,
  "accessPermission": ["READ_USER"]
}

###
GET {{base_url}}/profileAccess HTTP/1.1
Content-Type: {{contentType}}
